version: '3'

services: 
    oit:
        build: .
        volumes: 
            - oit_output:/home/oit/outputs
            - oit_samplefiles:/home/oit/samplefiles
            - oit_fonts:/home/oit/fonts
        ports: 
            - 8080:8888

volumes: 
    oit_fonts:
    oit_output:
    oit_samplefiles:
