version: '3'

services: 
    oit:
        build: .
        volumes: 
            - oit_output:/home/oit/outputs
            - oit_samplefiles:/home/oit/samplefiles
            - oit_fonts:/home/oit/fonts
        command: ["bash", "start.sh"]
        # command: ["java", "-cp", "oilink.jar:oitsample.jar", "OITSample", "/home/oit/samplefiles/adobe-acrobat.pdf", "/home/oit/outputs/test.tif", "tiff", "/home/oit/fonts"]
        # command: ["./exsimple", "/home/oit/samplefiles/adobe-acrobat.pdf", "/home/oit/outputs/testsimple.tif", "default.cfg"]

volumes: 
    oit_fonts:
    oit_output:
    oit_samplefiles: